name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Build Hugo Site"]
    types:
      - completed
    branches:
      - main

jobs:
  check-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      has_tag: ${{ steps.check_tag.outputs.has_tag }}
      tag_name: ${{ steps.check_tag.outputs.tag_name }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for tag on commit
        id: check_tag
        run: |
          # Get the SHA of the commit that triggered the workflow run
          SHA="${{ github.event.workflow_run.head_sha }}"
          
          # Check if this commit has a tag
          TAG=$(git tag --points-at $SHA)
          
          if [ -n "$TAG" ]; then
            echo "has_tag=true" >> $GITHUB_OUTPUT
            echo "tag_name=$TAG" >> $GITHUB_OUTPUT
            echo "Found tag $TAG for commit $SHA"
          else
            echo "has_tag=false" >> $GITHUB_OUTPUT
            echo "No tag found for commit $SHA"
          fi

  build-and-push-image:
    needs: check-tag
    runs-on: ubuntu-latest
    if: ${{ needs.check-tag.outputs.has_tag == 'true' }}
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download Hugo site artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: hugo-build.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: hugo-site-build
          path: site-content

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: |
          TAG_NAME="${{ needs.check-tag.outputs.tag_name }}"
          # Remove 'v' prefix if present for semantic versioning
          CLEAN_TAG=${TAG_NAME#v}
          echo "clean_tag=$CLEAN_TAG" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.extract_tag.outputs.clean_tag }}
            type=semver,pattern={{version}},value=${{ steps.extract_tag.outputs.clean_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.extract_tag.outputs.clean_tag }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.release
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}